languageCode = "en-us"
title = "Kenny Chow"
baseurl = "https://kenny.chow.my/"
theme = "aerial"
enableRobotsTXT = true

[params]
  name = "Kenny Chow"
  about = "Java | ReactJS | Full Stack | API | Security | Architecture | 程序员 | 
容器编排"
  copyright = ""
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "no"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/kennychowmy?lang=en"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/kenny-chow-my"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/kennychow"
