languageCode = "en-us"
title = "Kenny Chow"
baseurl = "https://kenny.chow.my/"
theme = "aerial"
enableRobotsTXT = true

[params]
  name = "Kenny Chow"
  about = "Product | Engineer | API | Security | Architecture "
  copyright = ""
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "no"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/kennychowmy?lang=en"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/kenny-chow-my"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/kennychow"
  
[[redirects]]
  from = "/redir301"
  to = "https://static.developer.mastercard.com/content/mcapi/blog/dont-be-a-minimum-viable-product-manager/index.social"
  status = 301
  force = true

[[redirects]]
  from = "/redir302"
  to = "https://static.developer.mastercard.com/content/mcapi/blog/api-tough-love/index.social"
  status = 302
  force = true
