[[redirects]]
  from = "/redir301"
  to = "https://static.developer.mastercard.com/content/mcapi/blog/dont-be-a-minimum-viable-product-manager/index.social"
  status = 301
  force = true

[[redirects]]
  from = "/redir302"
  to = "https://static.developer.mastercard.com/content/mcapi/blog/api-tough-love/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/redirckm"
  to = "https://cheerfulkidsmusic.com/program/"
  status = 302
  force = true


[[redirects]]
  from = "/redir304"
  to = "https://developer.mastercard.com"
  status = 302
  force = true

[[redirects]]
  from = "/redir305"
  to = "https://developers.mastercard.com"
  status = 302
  force = true
